name: Reset Database

on:
  workflow_dispatch:

jobs:
  reset-db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: database-testing

      - name: SQLite Setup
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3

      - name: Run SQL script to reset database
        run: |
          sqlite3 CurriculadoraDB/CurriculadoraDatabase.db < CurriculadoraDB/Curriculadora_Reset_Script.sql
        env:
          DATABASE_PATH: ./CurriculadoraDB/CurriculadoraDatabase.db  

      - name: SSH Setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_REPO_KEY }}
        
      - name: Switch from HTTPS to SSH
        run: git remote set-url origin git@github.com:TuitionScheduler/curriculadora.git

      - name: Github User Setup
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
  
      - name: Checkout database-testing branch
        run: git checkout database-testing
        
      - name: Check for file changes
        run: git status
        
      - name: Stage changed files
        run: git add .
        
      - name: Commit changed files
        run: git commit -m "Reset DB"
        
      - name: Fetch from database-testing branch
        run: git fetch origin database-testing
        
      - name: Push code to database-testing branch
        run: git push origin HEAD:database-testing
