name: Reset Database

on:
  workflow_dispatch:

jobs:
  reset-db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: database-testing

      - name: SQLite Setup
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3

      - name: Run SQL script to reset database
        run: |
          sqlite3 CurriculadoraDB/CurriculadoraDatabase.db < CurriculadoraDB/CurriculadoraScript.sql
        env:
          DATABASE_PATH: ./CurriculadoraDB/CurriculadoraDatabase.db  

      - name: SSH Setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        
      - name: Switch from HTTPS to SSH
        run: git remote set-url origin git@github.com:TuitionScheduler/curriculadora.git
  
      - name: Checkout database-testing branch
        run: git checkout database-testing
        
      - name: Check for file changes
        run: git status
        
      - name: Stage changed files
        run: git add .
        
      - name: Commit changed files
        run: git commit -m "Reset DB"
        
      - name: Fetch from database-testing branch
        run: git fetch origin database-testing
        
      - name: Push code to database-testing branch
        run: git push origin HEAD:database-testing
