name: Reset Database

on:
  push:
    branches:
      - database-testing
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/reset_db.yml

jobs:
  reset-db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: database-testing

      - name: SQLite Setup
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3

      - name: Run SQL script to reset database
        run: |
          sqlite3 database-testing/CurriculadoraDB/CurriculadoraDatabase.db < database-testing/CurriculadoraDB/CurriculadoraScript.sql
        env:
          DATABASE_PATH: ./database-testing/CurriculadoraDB/CurriculadoraDatabase.db  
